# Generated by Django 3.1.7 on 2021-02-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('firstname', models.CharField(blank=True, default='', max_length=40)),
                ('lastname', models.CharField(blank=True, default='', max_length=40)),
                ('github_username', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'ordering': ['lastname'],
            },
        ),
    ]
